version: '3.7'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Paris
      - TZ=Europe/Paris
      - N8N_AUTHENTICATION_DISABLED=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
