  services:
    n8n:
      image: docker.n8n.io/n8nio/n8n
      container_name: intellicorpus_n8n
      ports:
        - "5678:5678"
      environment:
        - GENERIC_TIMEZONE=Europe/Paris
        - TZ=Europe/Paris
        - N8N_AUTHENTICATION_DISABLED=true

        - DB_TYPE=postgresdb
        - DB_POSTGRESDB_HOST=intellicorpus_postgres
        - DB_POSTGRESDB_PORT=5432
        - DB_POSTGRESDB_DATABASE=intellicorpus
        - DB_POSTGRESDB_USER=intellicorpus_user
        - DB_POSTGRESDB_PASSWORD=intellicorpus_pwd
      volumes:
        - n8n_data:/home/node/.n8n
      depends_on:
        - intellicorpus_db

    intellicorpus_db:
      image: postgres:17
      restart: always
      environment:
        POSTGRES_USER: intellicorpus_user
        POSTGRES_PASSWORD: intellicorpus_pwd
        POSTGRES_DB: intellicorpus
        TZ: Europe/Paris
      ports:
        - "5433:5432"
      volumes:
        - intellicorpus_postgres_data:/var/lib/postgresql/data

  volumes:
    n8n_data:
    intellicorpus_postgres_data: